// Generated by CoffeeScript 1.9.0
(function() {
  var settings, winston;

  settings = require('./settings.json');

  winston = require('winston');

  if (process.env.VCAP_APPLICATION == null) {
    if (!settings.debug) {
      winston.remove(winston.transports.Console);
    }
    winston.add(winston.transports.File, {
      'filename': settings.log,
      'maxsize': 2000000,
      'maxFiles': 1,
      'json': false,
      'handleExceptions': true
    });
  } else {
    winston.remove(winston.transports.Console);
    winston.add(winston.transports.Console, {
      'handleExceptions': true,
      'timestamp': true
    });
  }

  module.exports = winston;

}).call(this);
