// Generated by CoffeeScript 1.6.1
(function() {

  exports.mass_update = require('./mass_update');

  exports.get_names = require('./get_names');

  exports.search = require('./search');

  exports.spectate = require('./spectate');

  exports.masterybook = require('./masterybook');

  exports.index = function(req, res) {
    res.charset = 'utf8';
    res.contentType('json');
    return res.send(JSON.stringify(req.lolclient_status));
  };

  exports.status = function(req, res) {
    var status;
    status = {
      'data': req.bridge_status,
      'server': req.server_id
    };
    res.charset = 'utf8';
    res.contentType('json');
    return res.send(JSON.stringify(status));
  };

}).call(this);
